//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shmap.UI.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shmap.UI.Localization.LocalizationStrings", typeof(LocalizationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number (Amazon).
        /// </summary>
        internal static string AmazonNumber {
            get {
                return ResourceManager.GetString("AmazonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name (Amazon).
        /// </summary>
        internal static string AmazonProductName {
            get {
                return ResourceManager.GetString("AmazonProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU (Amazon).
        /// </summary>
        internal static string AmazonSku {
            get {
                return ResourceManager.GetString("AmazonSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoFill.
        /// </summary>
        internal static string AutoFillTabTitle {
            get {
                return ResourceManager.GetString("AutoFillTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string AvailableLanguages {
            get {
                return ResourceManager.GetString("AvailableLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start conversion....
        /// </summary>
        internal static string BeginConversion {
            get {
                return ResourceManager.GetString("BeginConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose invoices.
        /// </summary>
        internal static string ChooseInvoices {
            get {
                return ResourceManager.GetString("ChooseInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose output location.
        /// </summary>
        internal static string ChooseOutputLocationTitle {
            get {
                return ResourceManager.GetString("ChooseOutputLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert transactions.
        /// </summary>
        internal static string ConvertTransactions {
            get {
                return ResourceManager.GetString("ConvertTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted: {0}.
        /// </summary>
        internal static string CovertedStockDataStatistics {
            get {
                return ResourceManager.GetString("CovertedStockDataStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customs declaration.
        /// </summary>
        internal static string CustomsDeclaration {
            get {
                return ResourceManager.GetString("CustomsDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default email:.
        /// </summary>
        internal static string DefaultEmail {
            get {
                return ResourceManager.GetString("DefaultEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupped by: {0}, count: {1}.
        /// </summary>
        internal static string GroupSummaryTitle {
            get {
                return ResourceManager.GetString("GroupSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Converter.
        /// </summary>
        internal static string InvoiceConverterTabTitle {
            get {
                return ResourceManager.GetString("InvoiceConverterTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string InvoiceItems {
            get {
                return ResourceManager.GetString("InvoiceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No invoices were converted!.
        /// </summary>
        internal static string InvoiceNotConvertedMsg {
            get {
                return ResourceManager.GetString("InvoiceNotConvertedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        internal static string InvoiceOrigin {
            get {
                return ResourceManager.GetString("InvoiceOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU codes.
        /// </summary>
        internal static string ItemsSkuCodes {
            get {
                return ResourceManager.GetString("ItemsSkuCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual change.
        /// </summary>
        internal static string ManualChangeTitle {
            get {
                return ResourceManager.GetString("ManualChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current length {0} out of {1} max.
        /// </summary>
        internal static string MaxLengthXOutOfN {
            get {
                return ResourceManager.GetString("MaxLengthXOutOfN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder after finished:.
        /// </summary>
        internal static string OpenFolderAfterOperationFinished {
            get {
                return ResourceManager.GetString("OpenFolderAfterOperationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity in pack.
        /// </summary>
        internal static string PackQuantity {
            get {
                return ResourceManager.GetString("PackQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous invoice № in Pohoda:.
        /// </summary>
        internal static string PreviousInvoiceNumberInPohoda {
            get {
                return ResourceManager.GetString("PreviousInvoiceNumberInPohoda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductCode.
        /// </summary>
        internal static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product code is not set!.
        /// </summary>
        internal static string ProductCodeIsNotSetValidationMsg {
            get {
                return ResourceManager.GetString("ProductCodeIsNotSetValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Updater.
        /// </summary>
        internal static string QuantityUpdaterTabTitle {
            get {
                return ResourceManager.GetString("QuantityUpdaterTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files.
        /// </summary>
        internal static string TextFilesExtensionDescription {
            get {
                return ResourceManager.GetString("TextFilesExtensionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions Converter.
        /// </summary>
        internal static string TransactionsConverterTabTitle {
            get {
                return ResourceManager.GetString("TransactionsConverterTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT type.
        /// </summary>
        internal static string VatType {
            get {
                return ResourceManager.GetString("VatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse code.
        /// </summary>
        internal static string WarehouseCode {
            get {
                return ResourceManager.GetString("WarehouseCode", resourceCulture);
            }
        }
    }
}
