name: CI

on:
  push:
    branches: 
    - dev 
    - master
  pull_request:
    branches: 
    - dev 
    - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.MAPP_PAT }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore -m:1

      - name: Test
        run: dotnet test --no-restore --verbosity minimal
